package com.mebk.pan.utils

//debug环境
const val CONFIGURE_DEBUG = true

//download_work_tag
const val DOWNLOAD_KEY_OUTPUT_FILE_ID = "DOWNLOAD_KEY_OUTPUT_FILE_ID"
const val DOWNLOAD_KEY_OUTPUT_FILE = "DOWNLOAD_KEY_OUTPUT_FILE"
const val DOWNLOAD_KEY_OUTPUT_FILE_NAME = "DOWNLOAD_KEY_OUTPUT_FILE_NAME"
const val DOWNLOAD_KEY_INPUT_FILE_CLIENT = "DOWNLOAD_KEY_INPUT_FILE_CLIENT"
const val DOWNLOAD_KEY_INPUT_FILE_SIZE = "DOWNLOAD_KEY_INPUT_FILE_SIZE"
const val DOWNLOAD_KEY_OUTPUT_FILE_DATE = "DOWNLOAD_KEY_OUTPUT_FILE_DATE"
const val DOWNLOAD_KEY_OUTPUT_FILE_TYPE = "DOWNLOAD_KEY_OUTPUT_FILE_TYPE"
const val DOWNLOAD_KEY_PROGRESS = "DOWNLOAD_KEY_PROGRESS"
const val DOWNLOAD_TAG = "DOWNLOAD_TAG"

//通知
const val NOTIFICATION_DOWNLOAD_NAME = "下载"
const val NOTIFICATION_DOWNLOAD_TITLE = "正在下载"
const val NOTIFICATION_DOWNLOAD_DESCRIBE = "显示当前下载任务"
const val NOTIFICATION_DOWNLOAD_CHANNEL_ID = "DOWNLOAD_CHANNEL_ID"
const val NOTIFICATION_DOWNLOAD_ID = 1

//请求
const val REQUEST_SUCCESS = "SUCCESS"
const val REQUEST_TIMEOUT = "TIMEOUT"
const val REQUEST_ERR = "ERR"

/*
* wait 等待下载 未获取链接
* prepare  获取链接 等待下载
* */
const val DOWNLOAD_STATE_WAIT = 0
const val DOWNLOAD_STATE_PREPARE = 1
const val DOWNLOAD_STATE_DOWNLOADING = 2
const val DOWNLOAD_STATE_CLIENT_ERR = 3
const val DOWNLOAD_STATE_DOWNLOAD_ERR = 4
const val DOWNLOAD_STATE_ERR = 5
const val DOWNLOAD_STATE_DONE = 6
const val DOWNLOAD_STATE_CANCEL = 7