package com.mebk.pan.utils

//debug环境
const val CONFIGURE_DEBUG = true
//download_work_tag
const val DOWNLOAD_KEY_OUTPUT_FILE_NAME="DOWNLOAD_KEY_OUTPUT_FILE_NAME"
const val DOWNLOAD_KEY_INPUT_FILE_CLIENT="DOWNLOAD_KEY_INPUT_FILE_CLIENT"
const val DOWNLOAD_KEY_INPUT_FILE_SIZE="DOWNLOAD_KEY_INPUT_FILE_SIZE"
const val DOWNLOAD_KEY_PROGRESS = "DOWNLOAD_KEY_PROGRESS"